export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const REGISTER = 'REGISTER';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
export const CHECKING_LOGIN_DONE = 'CHECKING_LOGIN_DONE';
export const SHOW_EMAIL_ALREADY_EXISTS_ERROR =
	'SHOW_EMAIL_ALREADY_EXISTS_ERROR';
export const SHOW_IMPROPER_EMAIL_OR_PASSWORD_ERROR =
	'SHOW_IMPROPER_EMAIL_OR_PASSWORD_ERROR';
export const SHOW_USER_NOT_EXIST_ERROR = 'SHOW_USER_NOT_EXIST_ERROR';
export const CLEAR_LOGIN_FORM_SUBMITTING_ERROR =
	'CLEAR_LOGIN_FORM_SUBMITTING_ERROR';
export const CLEAR_REGISTER_FORM_SUBMITTING_ERROR =
	'CLEAR_REGISTER_FORM_SUBMITTING_ERROR';
export const SEND_FORGOT_PASSWORD_RESET_LINK =
	'SEND_FORGOT_PASSWORD_RESET_LINK';
export const SENDING_FORGOT_PASSWORD_RESET_LINK =
	'SENDING_FORGOT_PASSWORD_RESET_LINK';
export const SEND_FORGOT_PASSWORD_RESET_LINK_SUCCESS =
	'SEND_FORGOT_PASSWORD_RESET_LINK_SUCCESS';
export const SEND_FORGOT_PASSWORD_RESET_LINK_SUCCESS_NOTIFIED =
	'SEND_FORGOT_PASSWORD_RESET_LINK_SUCCESS_NOTIFIED';
export const CLOSE_EMAIL_NOT_VERIFIED = 'CLOSE_EMAIL_NOT_VERIFIED';
export const VERIFICATION_EMAIL_SENT_SUCCESS =
	'VERIFICATION_EMAIL_SENT_SUCCESS';
export const VERIFICATION_EMAIL_MESSAGE_CLOSE =
	'VERIFICATION_EMAIL_MESSAGE_CLOSE';
